# AUTOGENERATED! DO NOT EDIT! File to edit: ../06_multicat.ipynb.

# %% auto 0
__all__ = ['path', 'img_files', 'cal', 'biwi', 'dls', 'xb', 'yb', 'learn', 'img2pose', 'get_ctr', 'sigmoid_range']

# %% ../06_multicat.ipynb 47
path = untar_data(URLs.BIWI_HEAD_POSE)

# %% ../06_multicat.ipynb 48
Path.BASE_PATH = path

# %% ../06_multicat.ipynb 51
img_files = get_image_files(path)

# %% ../06_multicat.ipynb 52
def img2pose(x): return Path(f'{str(x)[:-7]}pose.txt')

# %% ../06_multicat.ipynb 57
cal = np.genfromtxt(path/'01'/'rgb.cal', skip_footer=6)

# %% ../06_multicat.ipynb 60
def get_ctr(f):
    ctr = np.genfromtxt(img2pose(f), skip_header=3)
    c1 = ctr[0] * cal[0][0]/ctr[2] + cal[1][2]
    c2 = ctr[1] * cal[1][1]/ctr[2] + cal[1][2]
    return tensor([c1,c2])

# %% ../06_multicat.ipynb 62
biwi = DataBlock((ImageBlock, PointBlock),
                  get_items=get_image_files,
                  get_y=get_ctr,
                  splitter=FuncSplitter(lambda o: o.parent.name=='13'),
                  batch_tfms=aug_transforms(size=(240,320)),
                  )

# %% ../06_multicat.ipynb 63
dls = biwi.dataloaders(path)

# %% ../06_multicat.ipynb 65
xb, yb = dls.one_batch()
xb.shape, yb.shape

# %% ../06_multicat.ipynb 68
learn = vision_learner(dls, resnet18, y_range=(-1,1))

# %% ../06_multicat.ipynb 69
def sigmoid_range(x, lo, hi): return torch.sigmoid(x) * (hi-lo) + lo
